[workspace]
members = [
    "cargo-cage",
    "cage-core",
    "cage-cargo",
    "cage-linux",
    "cage-testkit",
]
resolver = "3"

[workspace.package]
version = "0.2.0"
edition = "2024"
rust-version = "1.85"
license = "Apache-2.0"
authors = ["NicDevTV"]
repository = "https://github.com/NicDev-Studios/Cargo-cage"
readme = "README.md"

[workspace.lints.rust]
unsafe_code = "forbid"
