[package]
name = "cargo-cage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
cage-cargo = { path = "../cage-cargo" }
cage-linux = { path = "../cage-linux" }

[dev-dependencies]
cage-core = { path = "../cage-core" }
cage-testkit = { path = "../cage-testkit" }
