[package]
name = "cargo-cage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true
description = "Run Cargo builds in an experimental Bubblewrap sandbox on Linux."
keywords = ["cargo", "sandbox", "security", "bubblewrap", "build-script"]
categories = ["command-line-utilities", "development-tools::cargo-plugins", "os"]
publish = true
exclude = ["tests/**"]

[lints]
workspace = true

[dependencies]
cage-cargo = { package = "cargo-cage-cargo", path = "../cage-cargo", version = "0.2.0" }
cage-linux = { package = "cargo-cage-linux", path = "../cage-linux", version = "0.2.0" }

[dev-dependencies]
cage-core = { package = "cargo-cage-core", path = "../cage-core" }
cage-testkit = { path = "../cage-testkit" }
